brew "bat"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fnm"
brew "fzf"
brew "jpegoptim"
brew "micro"
brew "oxipng"
brew "ripgrep"
brew "xcode-build-server"

cask "1password"
cask "alt-tab"
cask "cleanshot"
cask "equinox"
cask "figma"
cask "ghostty"
cask "google-chrome"
cask "raycast"
cask "sf-symbols"
cask "virtualbuddy"
cask "visual-studio-code"

mas "NextDNS", id: 1464122853
mas "Xcode", id: 497799835

cask "font-inter"
cask "font-jetbrains-mono"
cask "font-sf-compact"
cask "font-sf-mono"
cask "font-sf-pro"
