brew "bat"
brew "create-dmg"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fnm"
brew "fzf"
brew "gh"
brew "jpegoptim"
brew "micro"
brew "oxipng"
brew "ripgrep"
brew "rust"
brew "sentry-cli"
brew "xcbeautify"
brew "xcode-build-server"

cask "1password"
cask "1password-cli"
cask "alt-tab"
cask "apparency"
cask "archaeology"
cask "asset-catalog-tinkerer"
cask "cleanshot"
cask "deskpad"
cask "figma"
cask "ghostty"
cask "google-chrome"
cask "hammerspoon"
cask "homerow"
cask "iina"
cask "raycast"
cask "sf-symbols"
cask "sloth"
cask "virtualbuddy"
cask "visual-studio-code"

mas "Aqua Swatch", id: 1565479346
mas "Equinox", id: 1591510203
mas "Xcode", id: 497799835

cask "font-instrument-serif"
cask "font-inter"
cask "font-jetbrains-mono"
cask "font-sf-compact"
cask "font-sf-mono"
cask "font-sf-pro"
