[styles.tables]
headers = { color = "Gray", bold = true }

[styles.graphs]
graph_color = "DarkGray"

[styles.widgets]
border_color = "#2f363b"
disabled_text = { color = "DarkGray" }
selected_border_color = "Gray"
selected_text = { color = "Gray", bg_color = "#39576a" }
text = { color = "White" }
widget_title = { color = "Gray" }
