#!/bin/zsh

bar=(
  display="all"
  height=39
  color=0x00000000
  padding_left=16
  padding_right=16
)

defaults=(
  icon.drawing=off # There is 1px of reserved space even if you don't set an icon
  label.drawing=off # Same for labels...
  label.font="SF Pro:Medium:13"
  label.padding_right=1 # Some strings are clipped by 1 pixel
  update_freq=10
  padding_right=12
)

current_app_icon=(
  script="${CONFIG_DIR}/plugins/current_app.sh"
  update_freq=0
  background.drawing=on
  background.image.scale=0.5
  padding_right=6
)

current_app_name=(
  script="${CONFIG_DIR}/plugins/current_app.sh"
  update_freq=0
  label.drawing=on
  label.font="SF Pro:Bold:13"
)

next_event=(
  script="${CONFIG_DIR}/plugins/next_event.sh"
  click_script="${CONFIG_DIR}/helpers/GetNextEvent.swift --open-url"
  drawing=off
  label.drawing=on
  label.padding_left=8
  label.padding_right=8
  background.height=23
  background.corner_radius=8
  blur_radius=30
)

battery_status=(
  script="${CONFIG_DIR}/plugins/battery_status.sh"
  icon="􀛩"
  drawing=off
  icon.drawing=on
  icon.font="SF Pro:Light:15"
  icon.padding_left=3
  icon.padding_right=6
  label.drawing=on
)

date=(
  script="${CONFIG_DIR}/plugins/datetime.sh"
  update_freq=0
  label.drawing=on
  padding_right=6
)

time=(
  script="${CONFIG_DIR}/plugins/datetime.sh"
  label.drawing=on
  padding_right=0
)

sketchybar \
  --bar "${bar[@]}" \
  --default "${defaults[@]}" \
  --add event appearance_change "AppleInterfaceThemeChangedNotification" \
  --add event app_change \
  --add item current_app_icon left \
  --set current_app_icon "${current_app_icon[@]}" \
  --add item current_app_name left \
  --set current_app_name "${current_app_name[@]}" \
  --subscribe current_app_name appearance_change app_change \
  --add item time right \
  --set time "${time[@]}" \
  --subscribe time appearance_change system_woke \
  --add item date right \
  --set date "${date[@]}" \
  --add item battery_status right \
  --set battery_status "${battery_status[@]}" \
  --subscribe battery_status appearance_change system_woke power_source_change \
  --add item next_event right \
  --set next_event "${next_event[@]}" \
  --subscribe next_event appearance_change mouse.entered	mouse.clicked mouse.exited \
  --update

if pgrep -f "AppChange.swift" > /dev/null 2>&1; then
  pkill -f "AppChange.swift"
fi

${CONFIG_DIR}/events/AppChange.swift &
