#!/bin/zsh

source "${CONFIG_DIR}/colors.sh"

bar=(
  display=1 # Only on internal display (if "main" sketchybar will flash on external display when closing laptop screen)
  notch_display_height=37
  position=top
  color=0x00000000
  padding_left=15
  padding_right=15
)

defaults=(
  label.font="SF Pro:Medium:13"
  padding_right=15
)

current_app_icon=(
  script="${CONFIG_DIR}/plugins/current_app.sh"
  background.drawing=on
  padding_right=3
)

current_app_name=(
  script="${CONFIG_DIR}/plugins/current_app.sh"
  label.font="SF Pro:Bold:13"
  padding_left=1
)

next_meeting=(
  click_script="${CONFIG_DIR}/helpers/getNextMeeting.swift --open-url"
  script="${CONFIG_DIR}/plugins/next_meeting.sh"
  update_freq=10
  drawing=off
  icon="􂕝"
  icon.font="SF Pro:Regular:13"
  icon.color="${FOREGROUND_SECONDARY_LIGHT}"
  icon.padding_left=9
  icon.padding_right=7
  label.padding_right=10
  background.height=27
  background.corner_radius=8
  background.border_width=1
)

battery_status=(
  script="${CONFIG_DIR}/plugins/battery_status.sh"
  update_freq=60
  icon="􀛩"
  icon.font="SF Pro:Medium:15"
  icon.padding_left=2
  icon.padding_right=8
  label.font="SF Pro:Semibold:13"
)

date=(
  script="${CONFIG_DIR}/plugins/datetime.sh"
  padding_right=0
)

time=(
  script="${CONFIG_DIR}/plugins/datetime.sh"
  update_freq=10
  padding_left=6
  padding_right=2
)

sketchybar \
  --bar "${bar[@]}" \
  --default "${defaults[@]}" \
  --add event appearance_changed "AppleInterfaceThemeChangedNotification" \
  --add event date_changed "NSCalendarDayChangedNotification" \
  --add item current_app_icon left \
  --set current_app_icon "${current_app_icon[@]}" \
  --subscribe current_app_icon front_app_switched \
  --add item current_app_name left \
  --set current_app_name "${current_app_name[@]}" \
  --subscribe current_app_name appearance_changed front_app_switched \
  --add item time right \
  --set time "${time[@]}" \
  --subscribe time appearance_changed \
  --add item date right \
  --set date "${date[@]}" \
  --subscribe date appearance_changed date_changed \
  --add item battery_status right \
  --set battery_status "${battery_status[@]}" \
  --subscribe battery_status appearance_changed system_woke power_source_change \
  --add item next_meeting right \
  --set next_meeting "${next_meeting[@]}" \
  --subscribe next_meeting appearance_changed mouse.entered	mouse.clicked mouse.exited \
  --update
