#!/bin/zsh

bar=(
  display="all"
  height=39
  color=0x00000000
  padding_left=17
  padding_right=17
)

defaults=(
  label.font="SF Pro:Medium:13"
  update_freq=10
  padding_right=15
)

current_app_icon=(
  update_freq=0
  drawing=off
  background.drawing=on
  padding_right=6
  script="${CONFIG_DIR}/plugins/current_app.sh"
)

current_app_name=(
  update_freq=0
  label.font="SF Pro:Bold:13"
  script="${CONFIG_DIR}/plugins/current_app.sh"
)

next_event=(
  script="${CONFIG_DIR}/plugins/next_event.sh"
  click_script="${CONFIG_DIR}/helpers/GetNextEvent.swift --open-url"
  label.padding_left=8
  label.padding_right=8
  background.height=23
  background.corner_radius=8
  blur_radius=30
)

battery_status=(
  script="${CONFIG_DIR}/plugins/battery_status.sh"
  icon="􀛩"
  icon.font="SF Pro:Light:15"
  icon.padding_left=2
  icon.padding_right=6
)

date=(
  script="${CONFIG_DIR}/plugins/datetime.sh"
  update_freq=0
  padding_right=6
)

time=(
  script="${CONFIG_DIR}/plugins/datetime.sh"
  padding_right=0
)

sketchybar \
  --bar "${bar[@]}" \
  --default "${defaults[@]}" \
  --add event appearance_change "AppleInterfaceThemeChangedNotification" \
  --add event window_change \
  --add item current_app_icon left \
  --set current_app_icon "${current_app_icon[@]}" \
  --add item current_app_name left \
  --set current_app_name "${current_app_name[@]}" \
  --subscribe current_app_name appearance_change window_change \
  --add item time right \
  --set time "${time[@]}" \
  --subscribe time appearance_change system_woke \
  --add item date right \
  --set date "${date[@]}" \
  --add item battery_status right \
  --set battery_status "${battery_status[@]}" \
  --subscribe battery_status appearance_change system_woke power_source_change \
  --add item next_event right \
  --set next_event "${next_event[@]}" \
  --subscribe next_event appearance_change mouse.entered	mouse.clicked mouse.exited \
  --update \
  --trigger window_change BUNDLE_ID="" TITLE="👋  Greetings"
