export SNITCH_THEME="mono"

readonly FZF_BASE_COLORS="gutter:-1,fg:-1,fg+:-1,bg:-1,hl:4,hl+:4,marker:4"
readonly FZF_DARK_COLORS="bg+:#395263,info:8,spinner:8,border:8,scrollbar:8"
readonly FZF_LIGHT_COLORS="bg+:#b2c9d8,info:15,spinner:15,border:15,scrollbar:15"

ZSH_HIGHLIGHT_STYLES+=(
  alias "fg=4,bold"
  arg0 "fg=4,bold"
  autodirectory "fg=7,underline"
  back-dollar-quoted-argument "fg=5"
  back-double-quoted-argument "fg=5"
  builtin "fg=5,bold"
  command "fg=4,bold"
  comment "fg=8"
  dollar-double-quoted-argument "fg=5"
  double-hyphen-option "fg=3"
  double-quoted-argument "fg=2"
  function "fg=4,bold"
  global-alias "fg=3"
  globbing "fg=15"
  path "none"
  precommand "fg=5"
  redirection "fg=5"
  reserved-word "fg=5"
  single-hyphen-option "fg=3"
  single-quoted-argument "fg=2"
  suffix-alias "fg=7,underline"
  unknown-token "fg=1,bold"
)
